#!/bin/sh
#//////////////////////////////////////////////////
#//ServerLoader v1.x compatible DESLDaemon helper
#//	(C)2014-2022 Dark Embedded Systems.
#//	http://xprj.net/
#//////////////////////////////////////////////////

DSL_SELF="${0}";
DSL_FOLDER='/tmp/DESLDaemon/';
BIN_FOLDER=${BIN_FOLDER:-/DRoot/DarkSystem/bin};
CONF_FOLDER=${CONF_FOLDER:-/DRoot/DarkSystem/conf};
SERVICE_FOLDER="${CONF_FOLDER}/Services";

DESLDAEMON="${BIN_FOLDER}/DESLDaemon";

. ${BIN_FOLDER}/ConfigManager.sh

DSL_Header(){
cat <<"EOF";
:
: ServerLoader :: ServerLoader v1.x compatible DESLDaemon helper.
: http://xprj.net/
: (C)2014-2022 Dark Embedded Systems.
:
EOF
return 0;
}

show_usage(){
DSL_Header;

cat << EOF;

Run installed service:
	ServerLoader <start | once> <Service Name>

Run non-installed service:
	ServerLoader <start | once> <Service Name> <Dir> <App> [Args ...]

	e.g.) ServerLoader start telnetd /sbin telnetd -l /bin/sh

Control Service:
	ServerLoader <stop | restart | nowait> <Service Name>

Automatic start settings:
	ServerLoader <enable | disable> <Service Name>

List running services:
	ServerLoader list

EOF
return 0;
}

svc_start(){
	local SMode SName SDir SApp SArgs;
	SMode="${1}";

	[ "${3}" != "" ] && {
		shift; SName="${1}";
		shift; SDir="${1}";
		shift; SApp="${1}";
		shift; SArgs="${@}";
	} || {
		shift; SName="${1}";

		local SERVICE_FILE="${SERVICE_FOLDER}/${SName}.ini";
		[ ! -e "${SERVICE_FILE}" ] && {
			echo "E: Service: '${SName}' is not found."
			return 1;
		}

		config_load "${SERVICE_FILE}";

		config_get SDir Service:Dir -
		config_get SApp Service:App -
		config_get SArgs Service:Args ''
	}

	MODE='/Start';
	[ "${DSL_START_ONCE}" = "1" ] && MODE='/Once';

	exec ${DESLDAEMON} ${MODE} "${SName}" "${SDir}" "${SApp}" ${SArgs}
}

svc_once(){
	DSL_START_ONCE=1 svc_start "${@}"
}

svc_stop(){
	shift; local SName="${1}";
	exec ${DESLDAEMON} /Stop "${SName}"
}

svc_restart(){
	shift; local SName="${1}";
	exec ${DESLDAEMON} /Restart "${SName}"
}

svc_nowait(){
	shift; local SName="${1}";
	exec ${DESLDAEMON} /Nowait "${SName}"
}

svc_enable(){
	shift; SName="${1}";
	local SERVICE_FILE="${SERVICE_FOLDER}/${SName}.ini";
	[ ! -e "${SERVICE_FILE}" ] && {
		echo "E: Service: '${SName}' is not found."
		return 1;
	}

	mkdir -p "${SERVICE_FOLDER}/auto/";
	touch "${SERVICE_FOLDER}/auto/${SName}" || return 1;

	return 0;
}

svc_disable(){
	shift; SName="${1}";
	local SERVICE_FILE="${SERVICE_FOLDER}/${SName}.ini";

	rm -f "${SERVICE_FOLDER}/auto/${SName}" || return 1;

	return 0;
}

svc_auto(){
	for f in `ls "${SERVICE_FOLDER}/auto/"`; do
		echo "I: Starting '${f}'..."
		sleep 1
		${DSL_SELF} start ${f};
	done
	return 0;
}

svc_list(){
	exec ${DESLDAEMON} /List
}

main(){
	mkdir -p "${DSL_FOLDER}"

	case ${1} in
		"start"		) svc_start "${@}";;
		"stop"		) svc_stop "${@}";;
		"restart"	) svc_restart "${@}";;
		"once"		) svc_once "${@}";;
		"nowait"	) svc_nowait "${@}";;

		"enable"	) svc_enable "${@}";;
		"disable"	) svc_disable "${@}";;

		"auto"		) svc_auto "${@}";;
		"list"		) svc_list "${@}";;
		*		) show_usage;;
	esac

	return ${?};
}

main "${@}";

